django/kisaan/accounts/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth.decorators import login_required

from django.contrib.auth import views as auth_views

# SET THE NAMESPACE!
app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignupView.as_view(),name='signup'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='auth/change_password.html'), name='change_password'),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html',success_url=reverse_lazy('accounts:index'),redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html', email_template_name='auth/email/password_reset_email.txt',success_url=reverse_lazy('accounts:password_reset_sent')), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_sent.html'), name='password_reset_sent'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'), name='password_reset_complete'),

]

django/kisaan/dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'dashboard'

urlpatterns = [
    path('',login_required(views.IndexView.as_view()),name='index'),
    
]

django/kisaan/master/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'master'

urlpatterns = [
    path('create-state/',login_required(views.CreateState.as_view()),name='create_state'),
    path('list-state/',login_required(views.ListStateView.as_view()),name='list_state'),
    path('update-state/<str:pk>/',login_required(views.UpdateStateView.as_view()),name='update_state'),
    path('detail-state/<str:pk>/',login_required(views.DetailStateView.as_view()),name='detail_state'),
    path('delete-state/<str:pk>/',login_required(views.DeleteStateView.as_view()),name='delete_state'),
    path('create-zone/<str:state_id>',login_required(views.CreateZone.as_view()),name='create_zone'),
    path('list-zone/<str:state_id>',login_required(views.ListZoneView.as_view()),name='list_zone'),
    path('update-zone/<str:pk>/<str:state_id>',login_required(views.UpdateZoneView.as_view()),name='update_zone'),
    path('detail-zone/<str:pk>/<str:state_id>',login_required(views.DetailZoneView.as_view()),name='detail_zone'),
    path('delete-zone/<str:pk>/',login_required(views.DeleteZoneView.as_view()),name='delete_zone'),
    path('create-district/<str:state_id>/<str:zone_id>',login_required(views.CreateDistrict.as_view()),name='create_district'),
    path('list-district/<str:state_id>/<str:zone_id>',login_required(views.ListDistrictView.as_view()),name='list_district'),
    path('update-district/<str:pk>/<str:state_id>/<str:zone_id>',login_required(views.UpdateDistrictView.as_view()),name='update_district'),
    path('detail-district/<str:pk>/<str:state_id>/<str:zone_id>',login_required(views.DetailDistrictView.as_view()),name='detail_district'),
    path('delete-district/<str:pk>/',login_required(views.DeleteDistrictView.as_view()),name='delete_district'),


]

django/kisaan/mg_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('dashboard.urls')),
    path('api/', include('kisaan_api.urls')),

]

django/kisaan/dashboard/models.py
from django.db import models
import uuid

class WaterLevel(models.Model):
    id=models.UUIDField(default=uuid.uuid4(),primary_key=True)
    name = models.CharField(max_length=100)
    crop = models.CharField(max_length=100)
    temp = models.DecimalField(decimal_places=2,max_digits=4)
    humidity = models.DecimalField(decimal_places=2,max_digits=4)
    waterlevel = models.IntegerField()
    pressure  = models.DecimalField(decimal_places=2,max_digits=4)

    class Meta:
        db_table = "water_level"

django/kisaan/dashboard/views.py
from django.views.generic import (TemplateView, View,ListView)
# from institution.models import Institution
# from django.contrib.auth import get_user_model
# from master.models import District
# from course.models import Course
# from accounts.views import InstitutionUtility
from .models import WaterLevel
from django.http import JsonResponse, HttpResponse
# from django.core import serializers
import django_tables2 as tables,itertools
# from django.views.decorators.csrf import csrf_exempt
# from django.utils.decorators import method_decorator
#
class WaterLevelTable(tables.Table):

    s_no = tables.Column(empty_values=(),verbose_name = "S.No.")
    # students_num = tables.Column(verbose_name='No. of Students')
    # city_name = tables.Column(verbose_name='City')
    # zonecode= tables.Column(verbose_name = "Zone")
    # districtcode= tables.Column(verbose_name = "District")
    # statecode= tables.Column(verbose_name = "State")

    def __init__(self, *args, **kwargs):
         super(WaterLevelTable, self).__init__(*args, **kwargs)
         self.counter = itertools.count(start=1)

    def render_s_no(self):
         return '%d' % next(self.counter)

    class Meta:
        model = WaterLevel
        exclude = ('id',)
        attrs={"class":"table dataTable-collapse text-center dataTable no-footer mt0"}
        sequence = ('s_no',)



class IndexView(tables.SingleTableMixin,ListView):
    table_class = WaterLevelTable
    template_name = 'dashboard/index.html'
    table_pagination = {
        'per_page' : 15
    }

    def get_queryset(self):

        return WaterLevel.objects.all()




    def get_context_data(self, **kwargs):
        """
        Overridden version of `.TemplateResponseMixin` to inject the table into
        the template's context.
        """
        context = super(tables.SingleTableMixin, self).get_context_data(**kwargs)
        table = self.get_table(**self.get_table_kwargs())
        context[self.get_context_table_name(table)] = table

        

        return context
#
# @method_decorator(csrf_exempt, name='dispatch')
# class GetDistrictsView(View):
#
#     def get(self,request):
#         queryset = District.objects.all()
#         data = serializers.serialize('json',queryset)
#         return HttpResponse(data,content_type='application/json')
#
# @method_decorator(csrf_exempt, name='dispatch')
# class SessionDistrict(View):
#
#     def post(self,request):
#         district_id = request.POST.get('district_id')
#         if district_id != '0':
#             request.session['district'] = district_id
#         else :
#             del request.session['district']
#
#         return HttpResponse(district_id)

django/kisaan/templates/dashboard/partials/alert.html
{% if messages %}
<div class="alert alert-warning alert-main text-center" role="alert">
    {% for message in messages %}
    <strong class="text-capitalize"> {{ message }} </strong>
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
{% endif %}

django/kisaan/templates/dashboard/partials/footer.html
<!-- Footer Start -->
<div class="flex-grow-1"></div>
<div class="app-footer">

    <div class="footer-bottom">
        <span class="flex-grow-1"></span>
        <div class="text-center row">
            <div class="col-md-12">
                <p class="m-0">&copy; 2019 Recruitment Automation. All rights reserved.</p>
            </div>
        </div>
    </div>
</div>
<!-- fotter end -->

django/kisaan/templates/dashboard/partials/header.html
{% load static %}
<div class="main-header">

    <div class="logo">
        <img src="{% static "images/logo-tv.png" %}" alt="">
    </div>

    <div class="menu-toggle">
        <div></div>
        <div></div>
        <div></div>
    </div>

    <div style="margin: auto"></div>

    <div class="header-part-right">
      {% if user.profile_belongs_to_user.user_type != 2 %}
      <div class="d-flex align-items-center" id="districtSwitcher">
        <div class="key">
          <strong>District</strong>
        </div>
        <div class="value">
          <select id="selectDistrict" class="form-control select">
            <option value="0" selected> All Distircts</option>
          </select>
        </div>
      </div>

      {% endif %}
        <!-- User avatar dropdown -->
        <div class="dropdown">
            <div class="user colalign-self-end">
                <img src="{% static "images/admin.png" %}" id="userDropdown" alt="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <div class="dropdown-header">
                        <i class="i-Lock-User mr-1"></i> {{request.user.email}}
                    </div>
                    <a class="dropdown-item">Account settings</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign out</a>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="side-content-wrap">
    <div class="sidebar-left open rtl-ps-none" data-perfect-scrollbar data-suppress-scroll-x="true">
      <ul class="navigation-left">
          <li class="nav-item">
              <a class="nav-item-hold" href="{% url 'dashboard:index' %}">
                  <i class="nav-icon i-Bar-Chart"></i>
                  <span class="nav-text">Dashboard</span>
              </a>
              <div class="triangle"></div>
          </li>
        </ul>
    </div>
</div>

<script>

$(document).ready(function() {
  let district_id = '{{request.session.district}}';
  $.ajax({
    type:"GET",
    url:"/get-districts/",
    success: function(responseData,status,xhr){

      $.each(responseData,function(k,v){
        let attr = null;
        if(district_id===v.pk){
          attr = 'selected';
        }


        $('#selectDistrict').append('<option '+attr+' value = '+v.pk+'>'+v['fields'].name+'</option>');
      });
    }
  });

  $('#selectDistrict').on('change',function(){
    const id = $(this).val()
    $.ajax({
      type:"POST",
      data:{'district_id':id},
      url:"/set-session-district/",
      success: function(responseData,status,xhr){
          window.location=window.location.href
      }
    })

  })

  $('#selectDistrict').select2({
      width: '100%',
  });



});


</script>

django/kisaan/templates/dashboard/partials/search.html
<!-- ============ Search UI Start ============= -->
<div class="search-ui">
    <div class="search-header">
        <img src="./assets/images/logo.png" alt="" class="logo">
        <button class="search-close btn btn-icon bg-transparent float-right mt-2">
            <i class="i-Close-Window text-22 text-muted"></i>
        </button>
    </div>

    <input type="text" placeholder="Type here" class="search-input" autofocus>

    <div class="search-title">
        <span class="text-muted">Search results</span>
    </div>

    <div class="search-results list-horizontal">
        <div class="list-item col-md-12 p-0">
            <div class="card o-hidden flex-row mb-4 d-flex">
                <div class="list-thumb d-flex">
                    <!-- TUMBNAIL -->
                    <img src="./assets/images/products/headphone-1.jpg" alt="">
                </div>
                <div class="flex-grow-1 pl-2 d-flex">
                    <div class="card-body align-self-center d-flex flex-column justify-content-between align-items-lg-center flex-lg-row">
                        <!-- OTHER DATA -->
                        <a href="" class="w-40 w-sm-100">
                            <div class="item-title">Headphone 1</div>
                        </a>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">Gadget</p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">
                            $300
                            <del class="text-secondary">$400</del>
                        </p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100 d-none d-lg-block item-badges">
                            <span class="badge badge-danger">Sale</span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
        <div class="list-item col-md-12 p-0">
            <div class="card o-hidden flex-row mb-4 d-flex">
                <div class="list-thumb d-flex">
                    <!-- TUMBNAIL -->
                    <img src="./assets/images/products/headphone-2.jpg" alt="">
                </div>
                <div class="flex-grow-1 pl-2 d-flex">
                    <div class="card-body align-self-center d-flex flex-column justify-content-between align-items-lg-center flex-lg-row">
                        <!-- OTHER DATA -->
                        <a href="" class="w-40 w-sm-100">
                            <div class="item-title">Headphone 1</div>
                        </a>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">Gadget</p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">
                            $300
                            <del class="text-secondary">$400</del>
                        </p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100 d-none d-lg-block item-badges">
                            <span class="badge badge-primary">New</span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
        <div class="list-item col-md-12 p-0">
            <div class="card o-hidden flex-row mb-4 d-flex">
                <div class="list-thumb d-flex">
                    <!-- TUMBNAIL -->
                    <img src="./assets/images/products/headphone-3.jpg" alt="">
                </div>
                <div class="flex-grow-1 pl-2 d-flex">
                    <div class="card-body align-self-center d-flex flex-column justify-content-between align-items-lg-center flex-lg-row">
                        <!-- OTHER DATA -->
                        <a href="" class="w-40 w-sm-100">
                            <div class="item-title">Headphone 1</div>
                        </a>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">Gadget</p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">
                            $300
                            <del class="text-secondary">$400</del>
                        </p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100 d-none d-lg-block item-badges">
                            <span class="badge badge-primary">New</span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
        <div class="list-item col-md-12 p-0">
            <div class="card o-hidden flex-row mb-4 d-flex">
                <div class="list-thumb d-flex">
                    <!-- TUMBNAIL -->
                    <img src="./assets/images/products/headphone-4.jpg" alt="">
                </div>
                <div class="flex-grow-1 pl-2 d-flex">
                    <div class="card-body align-self-center d-flex flex-column justify-content-between align-items-lg-center flex-lg-row">
                        <!-- OTHER DATA -->
                        <a href="" class="w-40 w-sm-100">
                            <div class="item-title">Headphone 1</div>
                        </a>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">Gadget</p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100">
                            $300
                            <del class="text-secondary">$400</del>
                        </p>
                        <p class="m-0 text-muted text-small w-15 w-sm-100 d-none d-lg-block item-badges">
                            <span class="badge badge-primary">New</span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- PAGINATION CONTROL -->
    <div class="col-md-12 mt-5 text-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination d-inline-flex">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- ============ Search UI End ============= -->