django/kisaan/master/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'master'

urlpatterns = [
    path('create-state/',login_required(views.CreateState.as_view()),name='create_state'),
    path('list-state/',login_required(views.ListStateView.as_view()),name='list_state'),
    path('update-state/<str:pk>/',login_required(views.UpdateStateView.as_view()),name='update_state'),
    path('detail-state/<str:pk>/',login_required(views.DetailStateView.as_view()),name='detail_state'),
    path('delete-state/<str:pk>/',login_required(views.DeleteStateView.as_view()),name='delete_state'),
    path('create-zone/<str:state_id>',login_required(views.CreateZone.as_view()),name='create_zone'),
    path('list-zone/<str:state_id>',login_required(views.ListZoneView.as_view()),name='list_zone'),
    path('update-zone/<str:pk>/<str:state_id>',login_required(views.UpdateZoneView.as_view()),name='update_zone'),
    path('detail-zone/<str:pk>/<str:state_id>',login_required(views.DetailZoneView.as_view()),name='detail_zone'),
    path('delete-zone/<str:pk>/',login_required(views.DeleteZoneView.as_view()),name='delete_zone'),
    path('create-district/<str:state_id>/<str:zone_id>',login_required(views.CreateDistrict.as_view()),name='create_district'),
    path('list-district/<str:state_id>/<str:zone_id>',login_required(views.ListDistrictView.as_view()),name='list_district'),
    path('update-district/<str:pk>/<str:state_id>/<str:zone_id>',login_required(views.UpdateDistrictView.as_view()),name='update_district'),
    path('detail-district/<str:pk>/<str:state_id>/<str:zone_id>',login_required(views.DetailDistrictView.as_view()),name='detail_district'),
    path('delete-district/<str:pk>/',login_required(views.DeleteDistrictView.as_view()),name='delete_district'),


]

django/kisaan/mg_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('dashboard.urls')),
    path('api/', include('kisaan_api.urls')),

]

django/kisaan/master/models.py
from django.db import models

# Create your models here.


class State(models.Model):

    ACTIVE_CHOICES = (
        (0,'Inactive'),
        (1, 'Active'),
    )

    statecode = models.CharField(max_length=2, unique=True, primary_key=True)
    name = models.CharField(max_length=50)
    active = models.IntegerField(choices=ACTIVE_CHOICES)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.name

    class Meta:
        db_table = "master_state"



class Zone(models.Model):

    ACTIVE_CHOICES = (
        (0,'Inactive'),
        (1, 'Active'),
    )
    zonecode = models.CharField(max_length=4, unique=True, primary_key=True)
    statecode = models.ForeignKey(State, related_name="zone_belongs_to_state", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    active = models.IntegerField(choices=ACTIVE_CHOICES)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.name

    class Meta:
        db_table = "master_zone"


class District(models.Model):

    ACTIVE_CHOICES = (
        (0,'Inactive'),
        (1, 'Active'),
    )
    districtcode = models.CharField(max_length=4, unique=True, primary_key=True)
    statecode = models.ForeignKey(State, related_name="district_belongs_to_state", on_delete=models.CASCADE)
    zonecode = models.ForeignKey(Zone, related_name="district_belongs_to_zone", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    active = models.IntegerField(choices=ACTIVE_CHOICES)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.name

    class Meta:
        db_table = "master_district"

class Language(models.Model):
    id = models.CharField(max_length=2, unique=True, primary_key=True)
    name = models.CharField(max_length=5)
    timecreated = models.IntegerField()
    timemodified = models.IntegerField()

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.name

    class Meta:
        db_table = "languages"

django/kisaan/master/forms.py
from django import forms
from .models import State, Zone, District
from django.core import validators



class CreateStateForm(forms.ModelForm):
    name = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'id':'name', 'class':'form-control ', 'placeholder':'name'})
    )

    statecode = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'id':'statecode', 'class':'form-control ', 'placeholder':'code'})
    )

    active = forms.BooleanField(
        required = False,
        widget=forms.CheckboxInput(attrs={'id':'active', 'class':'form-control js-switch'})
    )

    class Meta():
        model = State
        fields = ('name','statecode','active')


class CreateZoneForm(forms.ModelForm):
    name = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'id':'zonename', 'class':'form-control ', 'placeholder':'name'})
    )

    zonecode = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'id':'zonecode', 'class':'form-control ', 'placeholder':'Zone Code'})
    )


    active = forms.BooleanField(
        required = False,
        widget=forms.CheckboxInput(attrs={'id':'activezone', 'class':'form-control js-switch'})
    )

    class Meta():
        model = Zone
        fields = ('name','zonecode','active')

class CreateDistrictForm(forms.ModelForm):
    name = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'id':'districtname', 'class':'form-control ', 'placeholder':'name'})
    )

    districtcode = forms.CharField(
        max_length=254,
        widget=forms.TextInput(attrs={'id':'districtcode', 'class':'form-control ', 'placeholder':'District Code'})
    )


    active = forms.BooleanField(
        required = False,
        widget=forms.CheckboxInput(attrs={'id':'activedistrict', 'class':'form-control js-switch'})
    )

    class Meta():
        model = District
        fields = ('name','districtcode','active')

django/kisaan/master/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import (TemplateView, CreateView, ListView, UpdateView, DetailView, DeleteView)
from .forms import CreateStateForm, CreateZoneForm, CreateDistrictForm
from django.urls import reverse_lazy
from .models import State, Zone, District
import django_tables2 as tables
import datetime
from django.db import IntegrityError, transaction
from django.contrib.auth import get_user_model
import time, itertools
from datetime import datetime

class CreateState(SuccessMessageMixin,CreateView):

    form_class = CreateStateForm
    model = State
    success_url = reverse_lazy('master:list_state')
    success_message="State created Successfully"
    template_name = 'master/create_state.html'

    def form_valid(self, form):
         return super(CreateState,self).form_valid(form)


class StateTable(tables.Table):
    action = tables.TemplateColumn(template_name='master/table_columns/edit.html')


    s_no = tables.Column(empty_values=(),verbose_name = "S.No.")

    def render_s_no(self):
         self.row_counter = getattr(self, 'row_counter',
                                   itertools.count(self.page.start_index()))
         return next(self.row_counter)

    class Meta:
        model = State
        exclude = ('is_deleted',)
        attrs={"class":"table table-striped table-full"}
        sequence = ('s_no',)

class ListStateView(tables.SingleTableView):
    model = State
    table_class = StateTable
    queryset = State.objects.filter(is_deleted=0)
    template_name = 'master/list_state.html'

class UpdateStateView(UpdateView):
    model = State
    form_class = CreateStateForm
    template_name = 'master/update_state.html'
    success_message = "Updated Successfully"
    def get_success_url(self):
        return reverse_lazy('master:detail_state',args=(self.kwargs['pk'],))

class DetailStateView(DetailView):
    model = State
    fields = ('name','is_active')
    template_name = 'master/detail_state.html'

class DeleteStateView(DeleteView):
    model = State

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('master:list_state')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = 1
        self.object.save()
        return HttpResponseRedirect(success_url)




class CreateZone(SuccessMessageMixin,CreateView):

    form_class = CreateZoneForm
    model = Zone
    success_message="State created Successfully"
    template_name = 'master/zone/create_zone.html'

    def get_success_url(self):
        return reverse_lazy('master:list_zone',args=(self.kwargs['state_id'],))

    def form_valid(self, form):
        form.instance.statecode = State.objects.get(statecode = self.kwargs['state_id'])
        return super(CreateZone,self).form_valid(form)


class ZoneTable(tables.Table):
    action = tables.TemplateColumn(template_name='master/table_columns/zone/edit.html')


    s_no = tables.Column(empty_values=(),verbose_name = "S.No.")

    def render_s_no(self):
         self.row_counter = getattr(self, 'row_counter',
                                   itertools.count(self.page.start_index()))
         return next(self.row_counter)

    class Meta:
        model = Zone
        exclude = ('is_deleted',)
        attrs={"class":"table table-striped table-full"}
        sequence = ('s_no',)

class ListZoneView(tables.SingleTableView):
    model = Zone
    table_class = ZoneTable
    queryset = Zone.objects.filter(is_deleted=0,statecode__is_deleted=0)
    template_name = 'master/zone/list_zone.html'

class UpdateZoneView(UpdateView):
    model = Zone
    form_class = CreateZoneForm
    template_name = 'master/zone/update_zone.html'
    success_message = "Updated Successfully"
    def get_success_url(self):
        return reverse_lazy('master:detail_zone',args=(self.kwargs['pk'],self.kwargs['state_id']))

class DetailZoneView(DetailView):
    model = Zone
    fields = ('name','statecode','active')
    template_name = 'master/zone/detail_zone.html'

class DeleteZoneView(DeleteView):
    model = Zone

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('master:list_zone')

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = 1
        self.object.save()
        return HttpResponseRedirect(success_url)

class CreateDistrict(SuccessMessageMixin,CreateView):

    form_class = CreateDistrictForm
    model = District
    success_message="District created Successfully"
    template_name = 'master/district/create_district.html'

    def get_success_url(self):
        return reverse_lazy('master:list_district',args=(self.kwargs['state_id'], self.kwargs['zone_id']))

    def form_valid(self, form):
        form.instance.statecode = State.objects.get(statecode = self.kwargs['state_id'])
        form.instance.zonecode = Zone.objects.get(zonecode = self.kwargs['zone_id'])
        return super(CreateDistrict,self).form_valid(form)


class DistrictTable(tables.Table):
    action = tables.TemplateColumn(template_name='master/table_columns/district/edit.html')


    s_no = tables.Column(empty_values=(),verbose_name = "S.No.")

    def render_s_no(self):
         self.row_counter = getattr(self, 'row_counter',
                                   itertools.count(self.page.start_index()))
         return next(self.row_counter)

    class Meta:
        model = District
        exclude = ('is_deleted',)
        attrs={"class":"table table-striped table-full"}
        sequence = ('s_no',)

class ListDistrictView(tables.SingleTableView):
    model = District
    table_class = DistrictTable
    queryset = District.objects.filter(is_deleted=0,statecode__is_deleted=0,zonecode__is_deleted=0)
    template_name = 'master/district/list_district.html'

class UpdateDistrictView(UpdateView):
    model = District
    form_class = CreateDistrictForm
    template_name = 'master/district/update_district.html'
    success_message = "Updated Successfully"
    def get_success_url(self):
        return reverse_lazy('master:detail_district',args=(self.kwargs['pk'],self.kwargs['state_id'],self.kwargs['zone_id']))

class DetailDistrictView(DetailView):
    model = District
    fields = ('name','statecode','zonecode','active')
    template_name = 'master/district/detail_district.html'

class DeleteDistrictView(DeleteView):
    model = District

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        state_id = District.objects.get(districtcode=self.kwargs['pk']).statecode
        zone_id = District.objects.get(districtcode=self.kwargs['pk']).zonecode
        return reverse_lazy('master:list_district',args=(state_id,zone_id))

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = 1
        self.object.save()
        return HttpResponseRedirect(success_url)

django/kisaan/master/templates/master/zone/_zoneform.html
{% load static %}
<form class="cozy" method="post">
  <div class="row">
    {% csrf_token %}

    {% if form.errors %}
    <div class="form-group mt-4  col-md-12 alert alert-danger">
      {{ form.errors }}
      {{ form.non_field_errors }}
    </div>
    {% endif %}


    <div class="form-group mt-4 col-md-6">
      {{ form.name }}
    </div>


    <div class="form-group mt-4 col-md-6">
      {{ form.zonecode }}
    </div>

    <div class="form-group mt-4 col-md-6">
    Active:  {{ form.active }}
    </div>



    <div class="form-group col-md-12 mt-4 d-flex align-items-center justify-content-between">
      <button type="submit" class="btn btn-primary btn-block">Create
        <i class="fas fa-long-arrow-alt-right ml-2"></i>
      </button>
    </div>
  </div>
</form>

{% block scripts %}
<script  src="{% static "vendors/switchery/switchery.min.js" %}" ></script>
<script  src="{% static "vendors/pickadate/picker.js" %}" ></script>
<script  src="{% static "vendors/pickadate/picker.date.js" %}" ></script>
<script>
  $(document).ready(function() {

    $('select').select2({
        width: '100%',
    });

    var elem = document.querySelector('.js-switch');
    var init = new Switchery(elem);

    $('.datepicker').pickadate({
      format: 'yyyy-mm-dd'
    });

  });
</script>
{% endblock %}

django/kisaan/master/templates/master/zone/create_zone.html
{% extends "dashboard/layouts/home.html" %}
{% block title %}Zone | Create{% endblock %}
{% load static %}

{% block body_block %}
<link rel="stylesheet" href="{% static "vendors/switchery/switchery.min.css" %}" >

<!-- ============ Body content start ============= -->
<div class="main-content-wrap sidenav-open d-flex flex-column">

  <div class="breadcrumb justify-content-between">
      <h1>Zone</h1>
      <ul>
          <li><a href="">Home</a></li>
          <li><a href="{% url 'master:list_state' %}">States</a></li>
          <li><a href="{% url 'master:list_zone' view.kwargs.state_id %}">Zones</a></li>
          <li>Create</li>
      </ul>
  </div>
  <div class="separator-breadcrumb border-top"></div>
    <div class="row pb-5">
        <div class="col-md-5">
          {% include "master/zone/_zoneform.html" %}

        </div>

    </div>

</div>
<!-- ============ Body content End ============= -->



{% endblock %}

django/kisaan/master/templates/master/zone/detail_zone.html
{% extends "dashboard/layouts/home.html" %}
{% block title %}State | Details{% endblock %}


{% load static %}

{% block body_block %}

<div class="main-content-wrap sidenav-open d-flex flex-column">

  <div class="breadcrumb justify-content-between">
      <h1>State</h1>
      <ul>
          <li><a href="">Home</a></li>
          <li><a href="{% url 'master:list_state' %}">State</a></li>
          <li><a href="{% url 'master:list_zone' view.kwargs.state_id %}">Zones</a></li>
          <li>Details</li>
      </ul>
  </div>
  <div class="separator-breadcrumb border-top"></div>
  <div class="card text-left">
    <div class="card-body p-0">
      <ul class="nav nav-tabs step-anchor nav-tabs-router">
         <li class="nav-item"><a href="{% url 'master:detail_zone' view.kwargs.pk view.kwargs.state_id %}" class="nav-link"> Details<br><small>Provide basic info like title, location etc.</small></a></li>
         <li class="nav-item"><a href="{% url 'master:update_zone' view.kwargs.pk view.kwargs.state_id %}" class="nav-link"> Update<br><small>Provide basic info like title, location etc.</small></a></li>
      </ul>
      <div class="row pb-5 mt-4">
          <div class="col-md-6 p-5">
            <ul>
              <li> <label>Name:</label> {{ zone.name }} </li>
              <li> <label>Zone:</label> {{ zone.zonecode }} </li>
              <li> <label>State:</label> {{ zone.statecode }} </li>
              <li>  <label>Active:</label> {{ zone.active }} </li>
            </ul>
          </div>

      </div>
    </div>
  </div>

</div>

{% block scripts %}
<script>
  $(document).ready(function() {

    $('select').select2({
        width: '100%',
    });

  });
</script>
{% endblock %}





{% endblock %}

django/kisaan/master/templates/master/zone/list_zone.html
{% extends "dashboard/layouts/home.html" %}
{% block title %}Zones{% endblock %}


{% load static %}

{% block body_block %}

<div class="main-content-wrap sidenav-open d-flex flex-column">
  <div class="breadcrumb justify-content-between">
      <h1>Zone</h1>
      <ul>
          <li><a href="">Home</a></li>
          <li><a href="{% url 'master:list_state' %}">State</a></li>
          <li>Zones</li>
      </ul>
      <a class="btn btn-md btn-primary float-right" href="{% url 'master:create_zone' view.kwargs.state_id %}">Add Zone</a>
  </div>
  <div class="separator-breadcrumb border-top"></div>

    <div class="row pb-5">
        <div class="col-md-12">
          <div class="card text-left">
              <div class="card-body p-0">
                {% load django_tables2 %}
                {% render_table table %}
              </div>
          </div>
        </div>
    </div>
</div>





{% endblock %}

django/kisaan/master/templates/master/zone/update_zone.html
{% extends "dashboard/layouts/home.html" %}
{% block title %}Zone | Update{% endblock %}


{% load static %}

{% block body_block %}
<link rel="stylesheet" href="{% static "vendors/switchery/switchery.min.css" %}" >

<div class="main-content-wrap sidenav-open d-flex flex-column">

  <div class="breadcrumb justify-content-between">
      <h1>Zone</h1>
      <ul>
          <li><a href="">Home</a></li>
          <li><a href="{% url 'master:list_state' %}">State</a></li>
          <li><a href="{% url 'master:list_zone' view.kwargs.state_id %}">Zones</a></li>
          <li>Update</li>
      </ul>
  </div>
  <div class="separator-breadcrumb border-top"></div>
  <div class="card text-left">
    <div class="card-body p-0">
      <ul class="nav nav-tabs step-anchor nav-tabs-router">
         <li class="nav-item"><a href="{% url 'master:detail_zone' view.kwargs.pk view.kwargs.state_id %}" class="nav-link"> Details<br><small>Provide basic info like title, location etc.</small></a></li>
         <li class="nav-item"><a href="{% url 'master:update_zone' view.kwargs.pk view.kwargs.state_id %}" class="nav-link"> Update<br><small>Provide basic info like title, location etc.</small></a></li>
     </ul>
      <div class="row pb-5 mt-4">
          <div class="col-md-6 p-5">
            {% include "master/zone/_zoneform.html" %}
          </div>

      </div>
    </div>
  </div>

</div>







{% endblock %}